### ISSUE TITLE
Kibana Dashboard

### ISSUE THREAD

**Issue by arosales** [juju-solutions/bundle-observable-kubernetes#10]
I did not know I needed to run an action to load the Kibana dashboard or what Kibana menus to traverse.  This bug is to make those instructions explicit to users. Specifically how to load the Kibana dashboard via the action and then what menus to traverse to see the data.

**Comment by johnsca** [comment]
There's now a config option to load the dashboard, as well.  Since the bundle includes the Beats charms, it should also include that config option.

**Comment by arosales** [comment]
@johnsca thanks for providing this via config option. This sounds like a lot cleaner solution.

Reopening this issue to ensure the README is documented on how the user should access the Kibana console.
