### ISSUE TITLE
Untar kube files into a directory

### ISSUE THREAD

**Issue by arosales** [juju-solutions/bundle-observable-kubernetes#11]
When I untar the kube files per the readme the untar command puts them down in my current working directory. It would be advantageous to un-tar the files into a "kubernetes-charm" directory so I can see what files were added and keep the filesystem better organized.

Current
```
$ tar -zxvf kubectl_package.tar.gz 
ca.crt
client.crt
client.key
kubeconfig
kubectl
```

suggest it looks like:

```
$tar -zxvf kubectl_package.tar.gz 
k8-charm/ca.crt
k8-charm/client.crt
k8-charm/client.key
k-charm/kubeconfig
k8-charm/kubectl
```

or something to that effect.

-thanks,
Antonio

**Comment by mbruzek** [comment]
Thanks for the feedback @arosales! The kubeconfig contains relative paths to the crt and the key. Adding a directory would cause me to change the code of the kuberentes charm how it builds the kubeconfig.

I can add something with the `-C` to output this to a directory and a link to more information on how to use kubectl.

**Comment by arosales** [comment]
> Thanks for the feedback @arosales! 

Thanks for the charms and bundles :-)

>The kubeconfig contains relative paths to the crt and the key. Adding a directory would cause me to change the code of the kuberentes charm how it builds the kubeconfig.
> 
> I can add something with the -C to output this to a directory and a link to more information on how to use kubectl.

I don't think you will need to change the paths. Even if you have the user output the files to a -C you just need to instruct the user to cd into the target directory and then run paths from that. For a better user experince and to follow convention suggest you tar up the directory with the files so you end up with something like:

```
$tar -zxvf kubectl_package.tar.gz 
k8-charm/ca.crt
k8-charm/client.crt
k8-charm/client.key
k-charm/kubeconfig
k8-charm/kubectl

$ cd k8-charm
$ ./kubectl cluster-health --config./kubeconfig  
```

then just have the user `cd k8-charm` then run commands from there. AIUI the paths wouldn't have to change. You could instruct the user what to explicitly do, the files are organized, follows convention, and if users don't go step by step they are not surprised from the un-tar.
