### ISSUE TITLE
kubectl commands need a --config

### ISSUE THREAD

**Issue by arosales** [juju-solutions/bundle-observable-kubernetes#13]
kubectl commands need a "--config kubeconfig" in order for ReadMe instructions to work.  Readme instructions such as:

`./kubectl cluster-health`

don't work unless I append --config, such as 

`./kubectl cluster-health --config./kubeconfig`

**Comment by chuckbutler** [comment]
hey good catch. I think when we wrote these instructions up we had already moved the kubeconfig to the default location of $HOME/.kube/config
