### ISSUE TITLE
Make changes to pass the Cloud Weather Report 

### ISSUE THREAD

**Issue by mbruzek** [juju-solutions/bundle-observable-kubernetes#26]
Make the changes necessary to pass the automated testing environment called cloud weather report (CWR).

We may need to scale back some of the high constraints on our bundle.
We may need to update to the latest versions.
We may need to make some changes to the bundle tests or test.yaml file for how the tests are run.

Just get the test to pass!

**Comment by arosales** [comment]
If you guys are using resources then you are tied to Juju 2.0.  Thus options going forward to have CWR pass are:
- Enable a code path for Juju 1.25 (non-resource)
- Enable CWR to support Juju 2.0 

For CWR and Juju 2.0 I think that is in plan, but proably won't happen until the August time frame.

**Comment by chuckbutler** [comment]
@mbruzek and @arosales - as you two have chimed in as the primary stakeholders on this issue, we have green reports now on http://status.juju.solutions

Is this representative of the quality we were seeking from this bug? Or are there additional work items to be had?

**Comment by mbruzek** [comment]
@chuckbutler thank you for the reminder on this issue. I think we have achieved the issue's goal based on the CWR green results: http://status.juju.solutions/test/b09b5a9473c4407bb58e020c614da755

We had to remove resources to get this to pass. It **is** August and we still don't have a 2.0 CWR.
