### ISSUE TITLE
bundle does not properly define options for `kubernetes` charm

### ISSUE THREAD

**Issue by chuckbutler** [juju-solutions/bundle-observable-kubernetes#37]
the proper format for declaring options in a yaml format is to specify it under the `options:` key

```
    options: 
      version: v1.3.4
```

the current bundle declares `version:` as a top level key, which is invalid.

**Comment by mbruzek** [comment]
Good find, I wonder who introduced this bug?

**Comment by chuckbutler** [comment]
Fixed in #38
