### ISSUE TITLE
Charm page instruction needs to be updated

### ISSUE THREAD

**Issue by takaakisuzuki** [juju-solutions/bundle-observable-kubernetes#44]
From:

$ juju run --service kubernetes is-leader
error: flag provided but not defined: --service

To:

ubuntu@OrangeBox88:/tmp/kubectl$ juju run --application kubernetes is-leader
- Stdout: |
     True
   UnitId: kubernetes/0
- Stdout: |
     False
   UnitId: kubernetes/1
- Stdout: |
     False
   UnitId: kubernetes/2

**Comment by takaakisuzuki** [comment]
@chuckbutler Can you check this url? https://jujucharms.com/observable-kubernetes/
the url include wrong command for juju2.0.

**Comment by chuckbutler** [comment]
Thanks for the clarification. This fix will go out with the next bundle release. Thanks for filing the bug 👍

**Comment by takaakisuzuki** [comment]
awesome. thanks for this :)
