### ISSUE TITLE
Expose Services

### ISSUE THREAD

**Issue by arosales** [juju-solutions/bundle-observable-kubernetes#9]
Suggest to expose services such as Kubernetes and Kibana, or at a minimum remind users they need to expose the service and then instructions on how to access the service.

**Comment by arosales** [comment]
I think we would rather error on folks having a good first user experience than security concerns. We should of course note in the readme which services are exposed by default and how to remove external access.

**Comment by mbruzek** [comment]
@arosales The bundle already exposes kibana and kubernetes. I will add a section about how to "unexpose" those nodes if they want.
